import { Bell,BookOpen,Briefcase,ChartNoAxesCombined,ChevronDown,FileText,GraduationCap,LayoutDashboard,LogOut,Menu,MessageSquare,Search,Settings,ShieldCheck,Users,X } from 'lucide-react';import { NavLink,Outlet,useLocation,useNavigate } from 'react-router-dom';import { useEffect,useState } from 'react';import Logo from './Logo';import { useAuth } from '../../context/AuthContext';import { notificationService } from '../../services/shared';import { countUnread,messageService } from '../../pages/messageService';
const sets={JOB_SEEKER:[['Overview','/job-seeker',LayoutDashboard],['Find jobs','/jobs',Search],['Applications','/job-seeker/applications',Briefcase],['My profile','/job-seeker/profile',Users],['CV builder','/job-seeker/cv',FileText],['My learning','/job-seeker/learning',GraduationCap],['Messages','/job-seeker/messages',MessageSquare],['Notifications','/job-seeker/notifications',Bell]],EMPLOYER:[['Overview','/employer',LayoutDashboard],['Manage jobs','/employer/jobs',Briefcase],['Applicants','/employer/applicants',Users],['Quiz builder','/employer/quizzes',FileText],['Messages','/employer/messages',MessageSquare],['Notifications','/employer/notifications',Bell],['Company profile','/employer/profile',Settings]],ADMIN:[['Overview','/admin',LayoutDashboard],['Users','/admin/users',Users],['Jobs','/admin/jobs',Briefcase],['Courses','/admin/courses',BookOpen],['Reports & analytics','/admin/reports',ChartNoAxesCombined],['Moderation','/admin/moderation',ShieldCheck],['Notifications','/admin/notifications',Bell]]};
export default function DashboardLayout(){
  const {user,logout}=useAuth();const nav=useNavigate();const location=useLocation();const [mobile,setMobile]=useState(false);
  const [unreadMessages,setUnreadMessages]=useState(0);const [unreadNotifications,setUnreadNotifications]=useState(0);
  useEffect(()=>{
    if(!user)return;
    messageService.getAll().then(list=>setUnreadMessages(countUnread(list,user.id))).catch(()=>{});
    notificationService.getAll().then(list=>setUnreadNotifications((list||[]).filter(n=>!n.is_read).length)).catch(()=>{});
  },[user?.id]);
  const badgeCounts={Messages:unreadMessages,Notifications:unreadNotifications};
  const links=sets[user?.role]||[];const title=links.find(([,path])=>location.pathname===path)?.[0]||'Workspace';const displayName=user?.name||user?.first_name||user?.email?.split('@')[0]||'User';const leave=()=>{logout();nav('/')};
  return <div className="app-shell"><aside className={mobile?'mobile-open':''}><div className="side-logo"><Logo/><button className="icon-btn side-close" onClick={()=>setMobile(false)}><X/></button></div><div className="workspace-label">{user?.role==='JOB_SEEKER'?'JOB SEEKER':user?.role}</div><nav>{links.map(([label,to,Icon])=><NavLink end to={to} key={to} onClick={()=>setMobile(false)}><Icon/>{label}{badgeCounts[label]>0&&<b>{badgeCounts[label]}</b>}</NavLink>)}</nav><div className="side-help"><div>✨</div><strong>Build your edge</strong><p>Complete your profile to get sharper matches.</p><NavLink to={user?.role==='JOB_SEEKER'?'/job-seeker/profile':'/courses'}>Continue</NavLink></div><button className="logout" onClick={leave}><LogOut/>Log out</button></aside><div className="dashboard-main"><header className="topbar"><button className="menu-btn" onClick={()=>setMobile(true)}><Menu/></button><div><small>SkillNet workspace</small><strong>{title}</strong></div><div className="top-actions"><label className="top-search"><Search/><input placeholder="Search SkillNet"/></label><NavLink to={user?.role==='ADMIN'?'/admin/notifications':user?.role==='EMPLOYER'?'/employer/notifications':'/job-seeker/notifications'} className="bell"><Bell/><i/></NavLink>{user?.role==='ADMIN'?<span className="user-menu"><span className="avatar">{displayName.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div className="user-name"><strong>{displayName}</strong><small>{user?.role?.replace('_',' ').toLowerCase()}</small></div><ChevronDown size={16}/></span>:<NavLink to={user?.role==='EMPLOYER'?'/employer/profile':'/job-seeker/profile'} className="user-menu"><span className="avatar">{displayName.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div className="user-name"><strong>{displayName}</strong><small>{user?.role?.replace('_',' ').toLowerCase()}</small></div><ChevronDown size={16}/></NavLink>}</div></header><main className="dashboard-content"><Outlet/></main></div></div>
}
