# Generated by Django 6.1 on 2026-08-13 08:28

import skillnet.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', skillnet.models.UserManager()),
            ],
        ),
    ]
