# Generated by Django 6.1 on 2026-08-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillnet', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
    ]
