# Generated by Django 6.1 on 2026-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillnet', '0003_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
    ]
