# Generated by Django 6.1 on 2026-09-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillnet', '0004_seekerprofile_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cv_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
