import { AlertCircle, ArrowRight, Briefcase, Check, ChevronRight, MapPin, Search, Star } from 'lucide-react';
import { Link } from 'react-router-dom';
export const Button=({children,variant='primary',className='',...props})=><button className={`btn btn-${variant} ${className}`} {...props}>{children}</button>;
export const Badge=({children,tone='default'})=><span className={`badge badge-${tone}`}>{children}</span>;
export const Avatar=({initials='SN',size='md'})=><span className={`avatar avatar-${size}`}>{initials}</span>;
export function PageHeader({eyebrow,title,description,actions}){return <div className="page-header"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="header-actions">{actions}</div>}</div>}
export function EmptyState({icon:Icon=Briefcase,title='Nothing here yet',description='New items will appear here.',action}){return <div className="empty-state"><span className="empty-icon"><Icon/></span><h3>{title}</h3><p>{description}</p>{action}</div>}
export const Spinner=()=> <div className="loading-state"><span className="spinner"/><span>Loading your workspace…</span></div>;
export const ErrorState=({message='Something went wrong. Please try again.'})=><div className="error-state"><AlertCircle/><div><strong>We couldn’t load this</strong><p>{message}</p></div></div>;
export function JobCard({job,compact=false}){return <article className={`job-card ${compact?'compact':''}`}><div className="job-top"><span className="company-logo" style={{background:job.color}}>{job.logo}</span><button className="icon-btn" aria-label="Save job">♡</button></div><div><p className="muted small">{job.company}</p><h3><Link to={`/jobs/${job.id}`}>{job.title}</Link></h3></div><div className="job-meta"><span><MapPin size={14}/>{job.location}</span><span><Briefcase size={14}/>{job.type}</span></div><div className="skills">{job.skills.slice(0,3).map(s=><Badge key={s}>{s}</Badge>)}</div><div className="job-foot"><div><strong>{job.salary}</strong><small>{job.posted}</small></div><Link className="round-link" to={`/jobs/${job.id}`} aria-label={`View ${job.title}`}><ArrowRight size={18}/></Link></div></article>}
export function CourseCard({course}){return <article className="course-card"><Link to={`/courses/${course.id}`} className={`course-art art-${course.image}`}><span>{course.skill}</span></Link><div className="course-body"><div className="row between"><Badge>{course.level}</Badge><span className="rating"><Star size={14} fill="currentColor"/>{course.rating}</span></div><h3><Link to={`/courses/${course.id}`}>{course.title}</Link></h3><p className="muted small">by {course.provider}</p><div className="course-foot"><span>{course.duration} · {course.lessons} lessons</span><strong>{course.price?`৳${course.price.toLocaleString()}`:'Free'}</strong></div></div></article>}
export function SearchBox({value,onChange,placeholder='Search'}){return <label className="search-box"><Search size={18}/><input value={value} onChange={onChange} placeholder={placeholder}/></label>}
export function StatCard({label,value,change,icon:Icon,tone='green'}){return <div className="stat-card"><div className={`stat-icon ${tone}`}>{Icon&&<Icon/>}</div><div><p>{label}</p><strong>{value}</strong>{change&&<small>{change}</small>}</div></div>}
export function StatusBadge({status}){const tone=status==='Hired'||status==='Interview'?'success':status==='Rejected'?'danger':status==='Shortlisted'?'purple':'default';return <Badge tone={tone}>{status}</Badge>}
export function Modal({open,onClose,title,children,footer}){if(!open)return null;return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><div className="modal-head"><h2>{title}</h2><button className="icon-btn" onClick={onClose}>×</button></div><div className="modal-body">{children}</div>{footer&&<div className="modal-foot">{footer}</div>}</section></div>}
export const Field=({label,error,children,hint})=><label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}{error&&<em>{error}</em>}</label>;
export const Stepper=({status})=>{const steps=['Applied','Shortlisted','Interview','Hired'];const rejected=status==='Rejected';const active=rejected?1:Math.max(0,steps.indexOf(status));return <div className="stepper">{steps.map((s,i)=><div className={`step ${i<=active&&!rejected?'done':''} ${i===active?'current':''}`} key={s}><span>{i<active?<Check size={14}/>:i+1}</span><small>{rejected&&i===2?'Rejected':s}</small>{i<steps.length-1&&<i/>}</div>)}</div>}
export const TableActions=()=> <button className="icon-btn">•••</button>;
export const ViewAll=({to,children='View all'})=><Link to={to} className="text-link">{children}<ChevronRight size={16}/></Link>;
